import CommentNode from '../renderer/CommentNode';
import ElementNode from '../renderer/ElementNode';
import ViewNode from '../renderer/ViewNode';
import TextNode from '../renderer/TextNode';
export { CommentNode, ElementNode, ViewNode, TextNode };
export declare const namespaceMap: {};
export declare function createElement(tagName: any, vnode: any): ElementNode;
export declare function createElementNS(namespace: any, tagName: any): ElementNode;
export declare function createTextNode(text: any): TextNode;
export declare function createComment(text: any): CommentNode;
export declare function insertBefore(parentNode: any, newNode: any, referenceNode: any): any;
export declare function removeChild(node: any, child: any): any;
export declare function appendChild(node: any, child: any): any;
export declare function parentNode(node: any): any;
export declare function nextSibling(node: any): any;
export declare function tagName(elementNode: any): any;
export declare function setTextContent(node: any, text: any): void;
export declare function setAttribute(node: any, key: any, val: any): void;
export declare function setStyleScope(node: any, scopeId: any): void;
